### ISSUE TITLE
UTF-8 Encoding Issues

### ISSUE THREAD

**Issue by codydh** [DGaffney/140kit_sandbox#2]
It seems like there's an outdated or incompatible file version here somewhere, as no matter what I've tried I keep getting UTF-8 encoding errors when workers start, and often crashes when trying to run analyses. Any hints?

**Comment by tony-pizza** [comment]
What ruby are you using? I remember having issues with 1.9.3 and some gems. A quick fix might be to try 1.9.2. @DGaffney might have more helpful insights.

Feel free to post your error trace and/or bundle show.

**Comment by codydh** [comment]
I am using Ubuntu 12.04, and Ruby 1.9.3. I don't think there are official 1.9.2 packages. Did you compile ruby from source, or are you using another distribution? I'm rebuilding to see if I can figure out anything as I go again, but I'll repost actual errors in a few once I get there.

**Comment by tony-pizza** [comment]
Hmm, yeah, not sure about the packages, but 1.9.2 is definitely out there. I installed 1.9.2 via RVM (https://rvm.io/), which I would highly recommend -- it makes installing and switching between rubies super easy.

**Comment by codydh** [comment]
Here's the main one I'm seeing all over:
<code>
/var/lib/gems/1.9.1/gems/data_objects-0.10.7/lib/data_objects/connection.rb:79: warning: Encoding UTF8 is not a known Ruby encoding for MySQL
</code>

I'm also getting an error when running many of the analytics that require UTF-8, but I'm not quite that far yet. I will give 1.9.2 a shot, would I have to start from scratch with 1.9.2, or just switch to that version and see if the already-installed gems work?

**Comment by codydh** [comment]
Here's another example:
<code>No analysis work to do right now.
Routing Analysis...
WordFrequency.run(1, 0.9)
Exiting.
Safely exited.
/root/140kit_sandbox/code/analyzer/tools/word_frequency.rb:18:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
        from /root/140kit_sandbox/code/analyzer/tools/word_frequency.rb:18:in`block in run'
        from /var/lib/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/collection.rb:507:in `block in each'
        from /var/lib/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in`block in each'
        from /var/lib/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
        from /var/lib/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in`each'
        from /var/lib/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/collection.rb:504:in `each'
        from /root/140kit_sandbox/code/analyzer/tools/word_frequency.rb:14:in`run'
        from worker.rb:161:in `route'
        from worker.rb:143:in`do_analysis_jobs'
        from worker.rb:45:in `work_routine'
        from worker.rb:35:in`block in work'
        from worker.rb:33:in `loop'
        from worker.rb:33:in`work'
        from worker.rb:175:in `<main>'
root@6s:~/140kit_sandbox/code/workers# </code>

**Comment by tony-pizza** [comment]
Ah, yes, I remember that one. I don't remember, however, if it's one that was immediately fixed by switching to 1.9.2. It is just a warning though -- I don't think it's actually causing an error.

I _think_ it was some weird bug in DO, but, regardless, you should check that your MySQL charset is set to utf8.

You would have to `bundle install` again to reinstall the gems after changing your ruby version. Your gempath suggests your using gems for ruby 1.9.1. though...

**Comment by tony-pizza** [comment]
Nevermind, there's an error!

**Comment by codydh** [comment]
Yeah, from what I can tell installing 1.9.3 on Ubuntu 12.04 is linking to 1.9.1, but ruby -v reveals 1.9.3.

I'll give rvm a shot with 1.9.2 and see what I can do!

**Comment by tony-pizza** [comment]
Cool, good luck!

RVM will setup separate gem homes for each ruby version, which is great :)

**Comment by codydh** [comment]
Well I installed and set up RVM, switched to 1.9.2-p320, did 'bundle install' in both code and rails, and when I start up worker.rb, I still get the same error :(

**Comment by codydh** [comment]
I spent some time doing a clean install on ruby1.9.2, and also trying to get the latest data_objects versions working. What I've noticed is that for the "code" database.yml, I can only do anything in that folder if I change all the adapters to "mysql" instead of "mysql2," whereas "mysql2" works fine in the rails folder. Could this be part of the problem?

**Comment by codydh** [comment]
Also seeing this error in importer.rb: 
<code>root@vps:~/140kit_sandbox/code/workers# ruby importer.rb
Class#validates_length is deprecated, use Class#validates_length_of instead (/root/140kit_sandbox/code/models/researcher.rb:36:in `class:Researcher')
Starting production environment...
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/data_objects-0.10.10/lib/data_objects/connection.rb:79: warning: Encoding UTF8 is not a known Ruby encoding for MySQL

Hello, my name is 6bbb2f9b049a7145f23cfab6911f46b296ea6b95.
Working...
Entering work routine.
Importing curation 6...
Exiting.
Safely exited.
/usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1892:in `block (2 levels) in shift': Unquoted fields do not allow \r or \n (line 1). (CSV::MalformedCSVError)
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1863:in`each'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1863:in `block in shift'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1825:in`loop'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1825:in `shift'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1767:in`each'
        from importer.rb:161:in `first'
        from importer.rb:161:in`block (4 levels) in import_datasets'
        from importer.rb:160:in `each'
        from importer.rb:160:in`block (3 levels) in import_datasets'
        from importer.rb:155:in `each'
        from importer.rb:155:in`block (2 levels) in import_datasets'
        from importer.rb:153:in `each'
        from importer.rb:153:in`block in import_datasets'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/dm-core-1.2.0/lib/dm-core/collection.rb:507:in `block in each'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in`block in each'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in `each'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/dm-core-1.2.0/lib/dm-core/support/lazy_array.rb:411:in`each'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/dm-core-1.2.0/lib/dm-core/collection.rb:504:in `each'
        from importer.rb:151:in`import_datasets'
        from importer.rb:37:in `work_routine'
        from importer.rb:28:in`block in work'
        from importer.rb:26:in `loop'
        from importer.rb:26:in`work'
        from importer.rb:220:in `<main>'
root@vps:~/140kit_sandbox/code/workers# </code>

**Comment by DGaffney** [comment]
lol
